name: CI/CT for each push
# env:
#   name: staging_environment

# concurrency: staging_environment

on:
  schedule:
    - cron: "00 12 * * *"
  push:
  pull_request:
    paths:
      - "**.js"
      - "!**/push.yml"
      - "build/**"
      - "release.json"
    branches: [main]
#
jobs:
  test-1:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [windows-latest, macos-latest]
        os: [ubuntu-latest, windows-2022, macos-latest]
        node-version: [14]
      fail-fast: false
    environment:
      name: CICD
    env:
      NODE_AUTH_TOKEN: ${{ secrets.PAT }}
      GITHUB_PAT: ${{ secrets.PAT }}
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      PHONE_NUMBER_ACCOUNT: ${{ secrets.PHONE_NUMBER_ACCOUNT }}
      PHONE_NUMBER_TOKEN: ${{ secrets.PHONE_NUMBER_TOKEN }}
      TEST1_EMAIL: ${{ secrets.TEST1_EMAIL }}
      TEST2_EMAIL: ${{ secrets.TEST2_EMAIL }}
      TEST3_EMAIL: ${{ secrets.TEST3_EMAIL }}
      TEST1_PHONE_NUMBER: ${{ secrets.TEST1_PHONE_NUMBER }}
      TEST2_PHONE_NUMBER: ${{ secrets.TEST2_PHONE_NUMBER }}
      TEST3_PHONE_NUMBER: ${{ secrets.TEST3_PHONE_NUMBER }}
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
      TEST_RESET_PASSWORD: ${{ secrets.TEST_RESET_PASSWORD }}
    steps:
      - name: Get short SHA 🔑
        id: slug
        run: |
          echo "::set-output name=sha7::${GITHUB_SHA::7}"
        shell: bash

      - name: Checkout ${{ steps.slug.outputs.sha7 }} ⬇️
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          registry-url: "https://npm.pkg.github.com"
          scope: "@zeeis"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT }}

      - name: Get message
        id: vars
        run: |
          git fetch --prune --unshallow
          echo "::set-output name=date::$(git log -1 --date=format:'%Y%m%d' --author="Alphabiz-Team" --format='%cd')"
          echo "::set-output name=current-hour::$(date +'%H')"
          if [[ ${{ matrix.os }} = "ubuntu-latest" ]] ; \
          then echo "::set-output name=system::ubuntu" ; \
          elif [[ ${{ matrix.os }} = "macos-latest" ]] ; \
          then echo "::set-output name=system::macos" ; \
          elif [[ ${{ matrix.os }} = "windows-2022" ]] ; \
          then echo "::set-output name=system::windows" ; \
          fi
          export MODIFIED_FILE_LIST=$(git show --pretty="format:" --name-only)
          echo "MODIFIED_FILE_LIST<<EOF" >> $GITHUB_ENV
          echo "$MODIFIED_FILE_LIST" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        shell: bash

      - name: Get last commit date \ today all commit message
        if: contains(steps.vars.outputs.current-hour, '12') || contains(env.MODIFIED_FILE_LIST, 'release.json')
        id: nightly
        run: |
          echo "::set-output name=commit::$(git log -1 --pretty=%B --author="Alphabiz-Team")"
          echo "::set-output name=commit-version::$(git log -1 --pretty=%B --author="Alphabiz-Team" | perl -wnE'say for /(?<=v)\d+\.\d+\.\d+/g')"
          echo "::set-output name=commit-date::$(git log -1 --pretty=%B --author="Alphabiz-Team" | perl -wnE'say for /(?<=-)\d{8,12}(?=-)/g')"
          echo "::set-output name=commit-sha7::$(git log -1 --pretty=%B --author="Alphabiz-Team" | perl -wnE'say for /(?<=-)\w{7}(?=\s)/g')"
          echo "::set-output name=commit-message::$(git log -1 --pretty=%B --author="Alphabiz-Team" | perl -wnE'say for /\d{8,12}-\w+/g')"
          export DESCRIBE=$(cat test/github-describe/github-describe.txt)
          echo "$DESCRIBE"
          echo "DESCRIBE<<EOF" >> $GITHUB_ENV
          echo "$DESCRIBE" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "contains(env.MODIFIED_FILE_LIST, 'release.json')"
          echo "${{ contains(env.MODIFIED_FILE_LIST, 'release.json') }}"
        shell: bash

      # 获取所以今天 作者为Alphabiz-Team的commit message,正则:不匹配'[-]符号'前面的任意字符、不匹配空行
      # export DESCRIBE=$(git log --reverse --after="${{ steps.vars.outputs.release-date }} 00:00" --before="${{ steps.vars.outputs.release-date }} 23:59" --author="Alphabiz-Team" --pretty='format:%B' | perl -wnE'say for /(?!.*-)(?!\s).*\w+$/gm')

      # because json file Multiline
      # need convert to a single line,then get property use fromJson().property
      - name: Get release.json property
        id: release
        if: contains(steps.vars.outputs.current-hour, '12') || contains(env.MODIFIED_FILE_LIST, 'release.json')
        run: |
          content=`cat ./release.json`
          content="${content//'%'/'%25'}"
          if [[ ${{ matrix.os }} = "macos-latest" ]] ; \
          then content="${content//$'\n'/%0A}" ; \
          else content="${content//$'\n'/'%0A'}" ; \
          fi
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=releaseJson::$content"
          echo "RELEASE_JSON<<EOF" >> $GITHUB_ENV
          echo "$content" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        shell: bash

      # This step for unify the tag name
      # nightly-release use tag_name: $packageJsonVersion-internal/nightly-$dateTime-$commitId
      # official-release use tag_name: ./release.json property new-tag-name
      - name: Unified Tag format
        if: contains(steps.vars.outputs.current-hour, '12') || contains(env.MODIFIED_FILE_LIST, 'release.json')
        id: unify
        run: |
          if ${{ contains(env.MODIFIED_FILE_LIST, 'release.json') }} ; \
          then echo "::set-output name=tag-name::${{ fromJson(steps.release.outputs.releaseJson).new-tag-name }}" ; \
               echo "::set-output name=release-name::${{ fromJson(steps.release.outputs.releaseJson).new-tag-name }}" ; \
               echo "::set-output name=build-version::${{ fromJson(steps.release.outputs.releaseJson).new-tag-name }}" ; \
          else echo "::set-output name=tag-name::${{ steps.nightly.outputs.commit-version }}-nightly-${{ steps.nightly.outputs.commit-message }}" ; \
               echo "::set-output name=release-name::${{ steps.nightly.outputs.commit-version }}-nightly-${{ steps.nightly.outputs.commit-sha7 }}" ;  \
               echo "::set-output name=build-version::${{ steps.nightly.outputs.commit-version }}-nightly-${{ steps.nightly.outputs.commit-date }}" ; \
          fi
        shell: bash

      # this step checkout all output
      - name: Checkout vars-date ${{ steps.vars.outputs.date }} ⬇️
        run: |
          echo "system: ${{ steps.vars.outputs.system }}"
          echo "run workflow date: ${{ steps.vars.outputs.date }}"
          echo "current-hour: ${{ steps.vars.outputs.current-hour }}"
          echo "----------------------"
          echo "MODIFIED_FILE_LIST: ${{ env.MODIFIED_FILE_LIST }}"
          echo "----------------------"
          echo "tag-name: ${{ steps.unify.outputs.tag-name }}"
          echo "release-name: ${{ steps.unify.outputs.release-name }}"
          echo "build-version: ${{ steps.unify.outputs.build-version }}"
          echo "----------------------"
          if ${{ contains(steps.vars.outputs.current-hour, '12') || contains(env.MODIFIED_FILE_LIST, 'release.json') }} ;\
          then  echo "commit: ${{ steps.nightly.outputs.commit }}" ; \
                echo "commit-version: ${{ steps.nightly.outputs.commit-version }}" ; \
                echo "commit-date: ${{ steps.nightly.outputs.commit-date }}" ; \
                echo "commit-sha7: ${{ steps.nightly.outputs.commit-sha7 }}" ; \
                echo "commit-message: ${{ steps.nightly.outputs.commit-message }}" ; \
          fi
        shell: bash

      - name: Checkout release.json target tag
        if: contains(env.MODIFIED_FILE_LIST, 'release.json')
        run: |
          git checkout ${{ fromJson(steps.release.outputs.releaseJson).target-tag-name }}
          git show --name-only
          echo "--------------------------"
          echo "target-tag-name: ${{ fromJson(steps.release.outputs.releaseJson).target-tag-name }}"
          echo "new-tag-name: ${{ fromJson(steps.release.outputs.releaseJson).new-tag-name }}"
          echo "--------------------------"
          echo "${{ env.RELEASE_JSON }}"
        shell: bash

      - name: Install dependencies 👨🏻‍💻
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT }}
          GITHUB_PAT: ${{ secrets.PAT }}

      - name: Install UnPackaged 👨🏻‍💻
        run: yarn unpackaged
        shell: bash

      - name: E2E Test for Electron 🧪
        run: yarn test:e2e:electron

      - name: E2E Test 🧪
        run: yarn test:e2e:ci

      - name: Upload Test Results 🗃
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: "${{ matrix.os }}-output"
          path: test/output/**

      #后面的step晚上运行 或 正式发布

      - name: Run electron-packager
        if: contains(steps.vars.outputs.current-hour, '12') || contains(env.MODIFIED_FILE_LIST, 'release.json')
        run: |
          export BUILD_VERSION=${{ steps.unify.outputs.build-version }}
          yarn packager
        shell: bash

      - name: Package for ${{ matrix.os }}-nightly-${{ steps.nightly.outputs.commit-message }} Release 🗜️
        if: contains(steps.vars.outputs.current-hour, '12') || contains(env.MODIFIED_FILE_LIST, 'release.json')
        run: 7z a -t7z -mx=9 alphabiz-${{ steps.unify.outputs.tag-name }}-${{ steps.vars.outputs.system }}.7z ./build/electron -xr!UnPackaged

      - name: Pack app 📦
        if: contains(steps.vars.outputs.current-hour, '12') || contains(env.MODIFIED_FILE_LIST, 'release.json')
        run: |
          export PATH=$PATH:/c/Program\ Files\ \(x86\)/WiX\ Toolset\ v3.11/bin
          export BUILD_VERSION=${{ steps.unify.outputs.build-version }}
          yarn make
        shell: bash

      - name: Release alphabiz-${{ steps.unify.outputs.tag-name }}-${{ steps.vars.outputs.system }}.7z to GitHub 📰
        if: contains(steps.vars.outputs.current-hour, '12') || contains(env.MODIFIED_FILE_LIST, 'release.json')
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          name: alphabiz-${{ steps.unify.outputs.release-name }}
          tag_name: ${{ steps.unify.outputs.tag-name }}
          body: ${{ env.DESCRIBE }}
          files: |
            alphabiz-${{ steps.unify.outputs.tag-name }}-${{ steps.vars.outputs.system }}.7z
            ./out/installers/${{ steps.unify.outputs.build-version }}/**
